# Logger setup
logging:
  level: "INFO"
  log_to_file: true
  log_directory: "logs"

# Default setup for collectors
defaults:
  wikipedia:
    collection_years: [2023]
    politicians: []
    political_topics: []
    political_events_template: ["{year} in politics"] ## This becomes e.g. "2023 in politics"

    data_output:
      directory: "data/raw"
      default_type: "wikipedia_data"
      separate_files_by_year: false

    api:
      language: ["en"]
      rate_limit_delay: 2.0
      max_retries: 3
      search_max_results: 5
      request_timeout: 30
      recursive_limit: 1 

# wikipedia_collector.py configuration
wikipedia:
  collection_years: [2023]

  politicians:
    en:
      - "Donald Trump Jr."
      - "Sir Keir Starmer"
      - "Emmanuel Macron"

    fr:
      - "Présidence d'Emmanuel Macron"

  political_topics:
    en:
      - "2024 United States presidential election"
      - "United Kingdom general election 2024"
      - "2024 French legislative election"

    fr:
      - "Élections législatives françaises de 2024"

  political_events_template:
    en:
      - "{year} in politics"

    fr:
      - "{year} en politique"

  data_output:
    directory: "data/raw"
    default_type: "wikipedia_all_political_data"
    separate_files_by_year: false
  
  api:
    language: ["en", "fr"]
    rate_limit_delay: 0.5
    max_retries: 5
    search_max_results: 10
    request_timeout: 10  